# Generated by Django 3.1.4 on 2020-12-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trophy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='Erhalten am')),
                ('title', models.TextField(verbose_name='Titel')),
                ('subtitle', models.TextField(verbose_name='Untertitel')),
                ('consumable', models.BooleanField(verbose_name='Verbrauchbar')),
                ('consumed_at', models.DateTimeField(blank=True, null=True, verbose_name='Verbraucht am')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link')),
                ('file', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
