# Generated by Django 3.1.4 on 2020-12-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guess',
            name='status',
            field=models.CharField(choices=[('SU', 'Geglückt'), ('FA', 'Gescheitert'), ('RU', 'Läuft')], default='RU', max_length=2),
        ),
    ]
