# Generated by Django 3.1.4 on 2020-12-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_trophy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guess',
            name='status',
            field=models.CharField(choices=[('SU', 'Geglückt'), ('FA', 'Gescheitert'), ('RU', 'Läuft'), ('CR', 'Erstellt')], default='CR', max_length=2),
        ),
    ]
