# Generated by Django 3.1.4 on 2020-12-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201221_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='trophy',
            name='expandable',
            field=models.BooleanField(default=False, verbose_name='Vergrösserbar'),
        ),
    ]
