# Generated by Django 3.1.4 on 2020-12-22 15:13

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201222_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trophy',
            name='file',
        ),
        migrations.AddField(
            model_name='trophy',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=''),
        ),
    ]
