# Generated by Django 3.1.4 on 2020-12-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_config'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config',
            options={'verbose_name': 'Konfiguration', 'verbose_name_plural': 'Konfiguration'},
        ),
        migrations.AlterModelOptions(
            name='dictionary',
            options={'verbose_name': 'Wort', 'verbose_name_plural': 'Wörter'},
        ),
        migrations.AlterModelOptions(
            name='guess',
            options={'verbose_name': 'Versuch', 'verbose_name_plural': 'Versuche'},
        ),
        migrations.AlterModelOptions(
            name='trophy',
            options={'verbose_name': 'Preis', 'verbose_name_plural': 'Preise'},
        ),
        migrations.AlterField(
            model_name='config',
            name='config',
            field=models.JSONField(blank=True, null=True, verbose_name='Konfiguration'),
        ),
    ]
